# 音频处理模型配置 | Audio Processing Model Configuration
# Copyright 2025 The AGI Brain System Authors
# Licensed under the Apache License, Version 2.0

# 基本配置 | Basic Configuration
model:
  name: "enhanced_audio_processing_model"
  version: "1.0.0"
  description: "增强型音频处理模型，支持语音识别、语调分析、音频合成等功能 | Enhanced audio processing model supporting speech recognition, tone analysis, audio synthesis, etc."
  author: "AGI Brain System Team"
  license: "Apache-2.0"

# 音频处理参数 | Audio Processing Parameters
audio:
  sample_rate: 16000
  frame_length: 1024
  hop_length: 256
  n_mels: 128
  n_fft: 2048
  max_audio_length: 30  # 最大音频长度（秒）| Maximum audio length (seconds)
  supported_formats:  # 支持的音频格式 | Supported audio formats
    - "wav"
    - "mp3"
    - "flac"
    - "ogg"
    - "m4a"

# 实时处理配置 | Real-time Processing Configuration
realtime:
  enabled: true
  buffer_size: 10  # 缓冲区大小 | Buffer size
  processing_interval_ms: 100  # 处理间隔（毫秒）| Processing interval (milliseconds)
  max_latency_ms: 500  # 最大允许延迟 | Maximum allowed latency
  auto_start: false  # 是否自动启动实时处理 | Whether to auto-start real-time processing

# 语音识别配置 | Speech Recognition Configuration
speech_recognition:
  model: "facebook/wav2vec2-large-960h-lv60-self"
  confidence_threshold: 0.7  # 置信度阈值 | Confidence threshold
  max_alternatives: 3  # 最大备选结果数 | Maximum number of alternative results
  language_detection: true  # 是否启用语言检测 | Whether to enable language detection
  supported_languages:  # 支持的语言 | Supported languages
    - "zh"  # 中文 | Chinese
    - "en"  # 英文 | English
    - "ja"  # 日文 | Japanese
    - "ko"  # 韩文 | Korean
    - "fr"  # 法文 | French
    - "de"  # 德文 | German
    - "es"  # 西班牙文 | Spanish
    - "ru"  # 俄文 | Russian

# 情感语调分析配置 | Emotion Tone Analysis Configuration
emotion_analysis:
  model: "superb/hubert-large-superb-er"
  emotion_categories:  # 情感类别 | Emotion categories
    - "neutral"    # 中性
    - "happy"      # 高兴
    - "sad"        # 悲伤
    - "angry"      # 愤怒
    - "fear"       # 恐惧
    - "disgust"    # 厌恶
    - "surprise"   # 惊讶
  intensity_threshold: 0.3  # 情感强度阈值 | Emotion intensity threshold

# 语音合成配置 | Speech Synthesis Configuration
speech_synthesis:
  enabled: true
  default_voice: "default"
  voice_types:  # 声音类型 | Voice types
    - "default"   # 默认
    - "child"     # 儿童
    - "elderly"   # 老年人
    - "male"      # 男性
    - "female"    # 女性
    - "robot"     # 机器人
    - "alien"     # 外星人
  emotion_types:  # 情感类型 | Emotion types
    - "neutral"   # 中性
    - "happy"     # 高兴
    - "sad"       # 悲伤
    - "angry"     # 愤怒
    - "excited"   # 兴奋
    - "calm"      # 平静
  sampling_rate: 22050  # 合成音频采样率 | Synthesis audio sample rate

# 音乐识别配置 | Music Recognition Configuration
music_recognition:
  enabled: true
  feature_extraction: true  # 是否提取音乐特征 | Whether to extract music features
  genres:  # 音乐流派 | Music genres
    - "pop"         # 流行
    - "rock"        # 摇滚
    - "jazz"        # 爵士
    - "classical"   # 古典
    - "electronic"  # 电子
    - "hiphop"      # 嘻哈
    - "country"     # 乡村
    - "blues"       # 蓝调
  bpm_range:  # BPM范围 | BPM range
    min: 60
    max: 200

# 噪音分析配置 | Noise Analysis Configuration
noise_analysis:
  enabled: true
  noise_types:  # 噪音类型 | Noise types
    - "background"  # 背景噪音
    - "white"       # 白噪音
    - "pink"        # 粉红噪音
    - "brown"       # 布朗噪音
    - "impulse"     # 脉冲噪音
    - "periodic"    # 周期性噪音
  intensity_levels:  # 强度级别 | Intensity levels
    - "low"         # 低
    - "medium"      # 中
    - "high"        # 高
  recommendation_enabled: true  # 是否提供处理建议 | Whether to provide processing recommendations

# 音频特效配置 | Audio Effects Configuration
audio_effects:
  enabled: true
  supported_effects:  # 支持的音效 | Supported audio effects
    - "echo"         # 回声
    - "reverb"       # 混响
    - "pitch_shift"  # 音高变换
    - "robot_voice"  # 机器人声音
    - "chorus"       # 合唱效果
    - "alien_voice"  # 外星人声音
    - "phaser"       # 相位器
    - "flanger"      # 法兰效果
    - "distortion"   # 失真效果
    - "compressor"   # 压缩器
  default_parameters:  # 默认参数 | Default parameters
    echo:
      delay: 0.5      # 延迟（秒）| Delay (seconds)
      decay: 0.5      # 衰减 | Decay
    reverb:
      room_size: 0.7  # 房间大小 | Room size
    pitch_shift:
      semitones: 2    # 半音数 | Number of semitones
    robot_voice:
      intensity: 0.8  # 强度 | Intensity

# 外部API配置 | External API Configuration
external_apis:
  use_external_api: false  # 是否使用外部API | Whether to use external APIs
  apis:
    google_speech:
      enabled: false
      name: "Google Speech-to-Text"
      url: "https://speech.googleapis.com/v1/speech:recognize"
      auth_method: "api_key"
      parameters:
        languageCode: "zh-CN"
        model: "default"
        enableAutomaticPunctuation: true
    openai_whisper:
      enabled: false
      name: "OpenAI Whisper"
      url: "https://api.openai.com/v1/audio/transcriptions"
      auth_method: "bearer_token"
      parameters:
        model: "whisper-1"
        response_format: "json"
    azure_speech:
      enabled: false
      name: "Azure Speech Services"
      url: "https://{region}.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1"
      auth_method: "subscription_key"
      parameters:
        language: "zh-CN"
        format: "detailed"
    amazon_transcribe:
      enabled: false
      name: "Amazon Transcribe"
      url: "https://transcribe.{region}.amazonaws.com"
      auth_method: "aws_signature"
      parameters:
        LanguageCode: "zh-CN"
        MediaFormat: "wav"

# 性能监控配置 | Performance Monitoring Configuration
performance:
  monitoring_enabled: true
  metrics:
    - "processing_time"     # 处理时间
    - "memory_usage"        # 内存使用
    - "recognition_accuracy" # 识别准确率
    - "synthesis_quality"   # 合成质量
    - "real_time_latency"   # 实时延迟
  sampling_interval: 60     # 采样间隔（秒）| Sampling interval (seconds)
  retention_period: 86400   # 数据保留时间（秒）| Data retention period (seconds)

# 日志配置 | Logging Configuration
logging:
  level: "INFO"  # 日志级别 | Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file_path: "logs/audio_model.log"  # 日志文件路径 | Log file path
  max_file_size: 10485760  # 最大文件大小（字节）| Maximum file size (bytes)
  backup_count: 5          # 备份文件数量 | Number of backup files
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # 日志格式 | Log format

# 输出配置 | Output Configuration
output:
  directory: "output"  # 输出目录 | Output directory
  file_naming: "timestamp"  # 文件命名方式 | File naming convention (timestamp, sequential, custom)
  formats:  # 输出格式 | Output formats
    audio:
      - "wav"
      - "mp3"
    text:
      - "json"
      - "txt"
    visualization:
      - "png"
      - "svg"
  quality_presets:  # 质量预设 | Quality presets
    low:
      bitrate: 64
      sample_rate: 16000
    medium:
      bitrate: 128
      sample_rate: 22050
    high:
      bitrate: 256
      sample_rate: 44100

# 资源限制 | Resource Limits
resources:
  max_memory_mb: 2048      # 最大内存使用（MB）| Maximum memory usage (MB)
  max_processing_threads: 4  # 最大处理线程数 | Maximum processing threads
  gpu_acceleration: true   # 是否启用GPU加速 | Whether to enable GPU acceleration
  batch_processing: true   # 是否启用批处理 | Whether to enable batch processing
  batch_size: 8            # 批处理大小 | Batch size

# 训练配置 | Training Configuration
training:
  enabled: false  # 是否启用训练功能 | Whether to enable training
  datasets:
    speech_recognition:
      path: "data/speech"
      formats:
        - "wav"
        - "txt"
    emotion_analysis:
      path: "data/emotion"
      formats:
        - "wav"
        - "json"
  hyperparameters:
    learning_rate: 0.001
    batch_size: 16
    epochs: 10
    validation_split: 0.2
  augmentation:  # 数据增强 | Data augmentation
    enabled: true
    techniques:
      - "noise_injection"
      - "time_stretch"
      - "pitch_shift"
      - "speed_change"

# 系统集成配置 | System Integration Configuration
integration:
  main_system:
    enabled: true
    communication_protocol: "http"  # 通信协议 | Communication protocol
    host: "localhost"
    port: 8000
    endpoint: "/api/audio/process"
    timeout: 30  # 超时时间（秒）| Timeout (seconds)
  data_bus:
    enabled: true
    topics:
      - "audio_input"
      - "audio_output"
      - "processing_status"
    serialization_format: "json"  # 序列化格式 | Serialization format
  web_interface:
    enabled: true
    port: 3000
    realtime_updates: true  # 是否启用实时更新 | Whether to enable real-time updates

# 安全配置 | Security Configuration
security:
  encryption:
    enabled: false
    algorithm: "AES-256"
    key_rotation: true
    rotation_interval: 86400  # 密钥轮换间隔（秒）| Key rotation interval (seconds)
  authentication:
    enabled: false
    method: "jwt"  # 认证方法 | Authentication method
    token_expiry: 3600  # token过期时间（秒）| Token expiry (seconds)
  data_privacy:
    enabled: true
    anonymization: false  # 是否启用数据匿名化 | Whether to enable data anonymization
    retention_policy: "30d"  # 数据保留策略 | Data retention policy

# 本地化配置 | Localization Configuration
localization:
  default_language: "zh"  # 默认语言 | Default language
  supported_languages:  # 支持的语言 | Supported languages
    - "zh"  # 中文
    - "en"  # 英文
  auto_detect: true  # 是否自动检测语言 | Whether to auto-detect language
  fallback_language: "en"  # 回退语言 | Fallback language

# 调试配置 | Debugging Configuration
debug:
  enabled: false
  features:
    - "detailed_logging"  # 详细日志
    - "performance_profiling"  # 性能分析
    - "memory_profiling"  # 内存分析
    - "input_validation"  # 输入验证
  log_level: "DEBUG"  # 调试日志级别 | Debug log level
